### ISSUE TITLE
Failed to install with node 12.18 with Invalid Package name

### ISSUE THREAD

**Issue by martin-jamszolik** [primefaces/primeflex#22]
See debug log below.

```sh
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/mjamsz/.nvm/versions/node/v12.18.1/bin/node',
1 verbose cli   '/home/mjamsz/.nvm/versions/node/v12.18.1/bin/npm',
1 verbose cli   'install',
1 verbose cli   'primeflex@1.3.0',
1 verbose cli   '--save'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose npm-session a9cb292aa10a7188
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/primeflex 210ms (from cache)
8 http fetch GET 200 https://registry.npmjs.org/primeflex/-/primeflex-1.3.0.tgz 10ms (from cache)
9 silly pacote version manifest for primeflex@1.3.0 fetched in 229ms
10 verbose stack Error: Invalid package name "__ngcc_entry_points__.json": name cannot start with an underscore
10 verbose stack     at invalidPackageName (/home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:86:15)
10 verbose stack     at Result.setName (/home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:121:11)
10 verbose stack     at new Result (/home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:111:23)
10 verbose stack     at Function.resolve (/home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:58:15)
10 verbose stack     at computeVersionSpec (/home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:320:21)
10 verbose stack     at Installer.normalizeCurrentTree (/home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install.js:410:68)
10 verbose stack     at Array.<anonymous> (/home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
10 verbose stack     at LOOP (/home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
10 verbose stack     at /home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
10 verbose stack     at /home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install.js:368:5
10 verbose stack     at /home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/iferr/iferr.js:3:64
10 verbose stack     at cb (/home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
10 verbose stack     at /home/mjamsz/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/call-limit/call-limit.js:28:43
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:79:11)
11 verbose cwd /home/mjamsz/dev/tefcor-ng
12 verbose Linux 5.6.19-300.fc32.x86_64
13 verbose argv "/home/mjamsz/.nvm/versions/node/v12.18.1/bin/node" "/home/mjamsz/.nvm/versions/node/v12.18.1/bin/npm" "install" "primeflex@1.3.0" "--save"
14 verbose node v12.18.1
15 verbose npm  v6.14.5
16 error code EINVALIDPACKAGENAME
17 error Invalid package name "__ngcc_entry_points__.json": name cannot start with an underscore
18 verbose exit [ 1, true ]

```

**Comment by martin-jamszolik** [comment]
My mistake, this was an npm package.json issue
