### ISSUE TITLE
"Errno::ENOENT: No such file or directory - primegrid.scss"

### ISSUE THREAD

**Issue by kounelios13** [primefaces/primeflex#4]
Hello.I have installed primeflex through npm.However when I install it and including I get the error above.
After opening node_module I opened `primegrid.css` and it had the following content:
```

/*
Errno::ENOENT: No such file or directory - primegrid.scss

Backtrace:
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/plugin/compiler.rb:454:in `read'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/plugin/compiler.rb:454:in `update_stylesheet'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/plugin/compiler.rb:215:in `block in update_stylesheets'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/plugin/compiler.rb:209:in `each'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/plugin.rb:82:in `update_stylesheets'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/exec/sass_scss.rb:340:in `watch_or_update'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/exec/sass_scss.rb:51:in `process_result'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/exec/base.rb:52:in `parse'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/lib/sass/exec/base.rb:19:in `parse!'
/Library/Ruby/Gems/2.0.0/gems/sass-3.5.5/bin/sass:13:in `<top (required)>'
/usr/local/bin/sass:23:in `load'
/usr/local/bin/sass:23:in `<main>'
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Errno::ENOENT: No such file or directory - primegrid.scss"; }
```

**Comment by mann-david** [comment]
Use primeflex.css instead of primegrid.css.  Works like a champ.

**Comment by mertsincan** [comment]
Thanks a lot, @mann-david ;)
