### ISSUE TITLE
Does not work with node.js 11.x

### ISSUE THREAD

**Issue by mp54214** [primefaces/primeflex#7]
After installing (in Angular) leads to the following error if node.js 11.x is used

ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (.....node_modules\sass-loader\lib\loader.js:46:72)

Obvious reason:  overwrites node-sass with older version which is not compatible with node.js 11.x
To fix, install latest node-sass right after installing primeflex:
   npm install node-sass@4.10.0 --no-save
see: https://github.com/angular/angular-cli/issues/12746

**Comment by mertsincan** [comment]
Thanks a lot for link, but I think this issue is not related to PrimeFlex.
